//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN_PORTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRECIO()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int PRECIOS_ID { get; set; }
        public double PRECIO_UNIDAD { get; set; }
        public Nullable<double> PRECIO_PAQUETE { get; set; }
        public Nullable<double> PRECIO_SERVICIO { get; set; }
        public Nullable<double> PRECIO_MAYOREO { get; set; }
        public Nullable<double> PRECIO_ESPECIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
