//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTNIMAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.EMPRESAS = new HashSet<EMPRESA>();
        }
    
        public int ID_CLIENT { get; set; }
        public string NOMBRE1_CLIENT { get; set; }
        public string NOMBRE2_CLIENT { get; set; }
        public string APELLIDO1_CLIENT { get; set; }
        public string APELLIDO2_CLIENT { get; set; }
        public string DIRECCION1_CLIENT { get; set; }
        public string CIUDAD_CLIENT { get; set; }
        public string DISTRITO_CLIENT { get; set; }
        public string CANTON_CLIENT { get; set; }
        public string PROVINCIA_CLIENT { get; set; }
        public string TELEF_CASA_CLIENT { get; set; }
        public string TELF_CELULAR_CLIENT { get; set; }
        public string EMAIL_CLIENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRESA> EMPRESAS { get; set; }
    }
}
